### ISSUE TITLE
Breaking change from v8.97.26 to v8.98.34 when trying to use OnnxEvaluator

### ISSUE THREAD

**Issue by danitico** [vespa-engine/vespa#25256]
**Describe the bug**
When upgrading from v8.97.26 to v8.98.34, there is a breaking change when trying to create an instance of the OnnxEvaluator. It fails in [OnnxEvaluator.java:37](https://github.com/vespa-engine/vespa/blob/fc0180434827f15a5678f964b428a264919921cc/model-integration/src/main/java/ai/vespa/modelintegration/evaluator/OnnxEvaluator.java#L37) with the error **(java.lang.NoClassDefFoundError: Could not initialize class ai.onnxruntime.OrtEnvironment** when we get the ort environment.

**To Reproduce**
1. Use version of 8.98.34
2. Create an instance of class OnnxEvaluator
3. See error

**Expected behavior**
It should get the ort environment correctly

**Screenshots**
No applicable

**Environment (please complete the following information):**
 - OS: Ubuntu, macOs
 - Infrastructure: self-hosted
 - Versions: Ubuntu 20.04, MacOs 13.0.1

**Vespa version**
8.98.34

**Comment by kkraune** [comment]
Hi, thanks for reporting! We found this issue this morning and are working on releasing a new version later today with a fix (will update here when done)

We will also add more testing to trap such problems before release - sorry for the inconvenience!

**Comment by gjoranv** [comment]
@danitico Until a fix is out, please add onnxruntime in test scope to your pom.xml:

´´´
        <dependency>
            <groupId>com.microsoft.onnxruntime</groupId>
            <artifactId>onnxruntime</artifactId>
            <version>1.12.0</version>
            <scope>test</scope>
        </dependency>
´´´

**Comment by kkraune** [comment]
Hi again! 8.99.32 is released; please try again and reopen if still an issue

**Comment by danitico** [comment]
Hi @kkraune, it's working! thanks!
