### ISSUE TITLE
Proton: Custom bucketing & Query

### ISSUE THREAD

**Issue by shwetanks** [vespa-engine/vespa#3709]
References:

id scheme

Format: id:<namespace>:<document-type>:<key/value-pairs>:<user-specified>

    http://docs.vespa.ai/documentation/content/buckets.html
    http://docs.vespa.ai/documentation/content/idealstate.html
its possible to structure data in user defined bucketing logic by using 32 LSB in document-id format (n / g selections).

however, the query logic isn't very clear on how to route queries to a specific bucket range based on a decision taken in advance.

e.g., it is possible to split data into a time range (start-time/end-time) if i can define n (a number) compressing the range. all documents tagged such will end up in same bucket (that will follow its course of split on number of documents / size as configured).

however, how do i write a search query on data indexed in such manner? is it possible to indicate the processor to choose a specific bucket, or range of buckets (in case distribution algorithm might have moved buckets)?

SO question here:
https://stackoverflow.com/questions/46681642/vespa-proton-custom-bucketing-query

i guess i am still seeking the right community to post general helpful questions, so any pointers to that are welcome as well.

**Comment by bratseth** [comment]
I answered on SO.

**Comment by shwetanks** [comment]
Thanks @bratseth 
could you advise how can we go forward with exploring if i can still create buckets by a user-defined criteria (as in key-value pairs defined in http://docs.vespa.ai/documentation/documents.html) and yet make use of indexed mode, and how to target that from search.

the data scale i am targeting will make such buckets have ~500million records (if it were to be a single bucket) that i want to split by a custom criteria (e.g. hourly time range) and leverage all benefits of indexed mode (e.g. stemming, linguisitics / normalization etc. are not available in streaming mode).

i've posted this in comments to your answer on SO question and wanted to attract your attention to that.

on other note, is Vespa planning to hold a webinar and open an IRC / group where devs can bounce off such ideas with contributors?..will help the community a lot.

Thank You!

**Comment by bratseth** [comment]
Yes, you definitely shouldn't use streaming for this, but also I don't think you need to use a custom bucketing scheme. Data is not physically stored separately per bucket, that would cause updates to be slow, they are just used as a data management unit. So the only thing you can hope to achieve by custom bucketing is to cause a skewed data distribution, which just reduces efficiency.

Just write all the documents straightforwardly, with a timestamp field marked as an attribute, and if that field is a strong criterion in queries, also mark it as fast-search.

Regarding IRC/group, someone was going to set up a Slack channel, I'll find out what happened about that. Would that work for you or do you think there's better option?

**Comment by shwetanks** [comment]
Thanks! Slack would be awesome but is a little uncontrolled (and i can't assume how the cost works out)!
any mailing list would do for start (e.g. apache has a lot of them) or even a google group would server well. SO will have a lot of relevant content to attract lesser github issues (i am mostly opening them to catalog initial questions that would otherwise take a lot of time to figure from vast documentation and source code, and of'course to help my greed of getting onboard faster!).

your confirmation about how we can openly structure data and yet operate at scale solves a lot of stuff! i can see how this is very different from elasticsearch approach of physical indices and elasticity is more of abstract data segments and several processes keeping watch on underlying system.

some side notes --

i've also compiled Vespa on debian (ubuntu) and apart from few changes, mostly in configuration, it went well (used gcc-6.3.0 and it spews segfaults on parallel build around sets & maps .. single thread build works). i'll however need a nod if there are any unknowns ahead if i'd want to submit a PR for a cleaner approach towards this (or why not to do that)
e.g. i had to add -Wno-format-security to address LOG(debug, const chat *) going without format specifier (this is at a lot of places) that Debian's default hardening doesn't allow. same is with -Wno-unused-result which is quite lax with CentOS.

thanks for help!

**Comment by baldersheim** [comment]
1 - segfaults on parallel builds -> That should not happen. Our internal builds run with -j  51 on our 48 core build machines. With no issues. The travis build I think runs with 4 cores. As far as I know there shall be no issues with parallel builds. If you encounter any that is a bug and needs to be rectified ASAP. Do you have any logs or anything that can help us narrow it down.

2 - We do not actively turn on -Wformat-security. I will give that a try and see what pops out. It sounds like something we should turn on.

3 - Same for -Wunused-result. That one might be a little harder to satisfy. I am not sure if these are OS dependent. If so we need to build on ubuntu too. I know we are doing RHEL 6, RHEL 7 and Centos 7 and Fedora 25/26.

If you find anything that should be improved feel free to submit pull request or give us hint. As long as your CLA is done we are open to any help.

**Comment by shwetanks** [comment]
1. parallel builds on ubuntu 14.04 gcc 6.3.0
gist with few logs
https://gist.github.com/shwetanks/6bc1230df2dd5e25e4698073eafae292#file-vespa_parallel_ubuntu-log

2. e.g. https://github.com/vespa-engine/vespa/blob/f76406b88df47f6bdbf9d24feda4c9ff55c63e06/filedistribution/src/vespa/filedistribution/distributor/filedownloader.cpp#L288

3. e.g. https://github.com/vespa-engine/vespa/blob/f76406b88df47f6bdbf9d24feda4c9ff55c63e06/vespalib/src/vespa/vespalib/net/selector.cpp#L45

----
additionally

`Building CXX object vespamalloc/src/vespamalloc/malloc/CMakeFiles/vespamalloc_mallocdst16.dir/threadpooldst.cpp.o

In file included from vespamalloc/src/vespamalloc/malloc/mallocdst16.cpp:32:0:
vespamalloc/src/vespamalloc/malloc/overload.h: In function ‘void* valloc(size_t)’:
vespamalloc/src/vespamalloc/malloc/overload.h:123:7: error: declaration of ‘void* valloc(size_t)’ has a different exception specifier
 void *valloc(size_t size)
       ^~~~~~
vespamalloc/src/vespamalloc/malloc/overload.h:122:7: note: from previous declaration ‘void* valloc(size_t) throw ()’
 void *valloc(size_t size) __attribute__((visibility ("default")));
       ^~~~~~
make[2]: *** [vespamalloc/src/vespamalloc/malloc/CMakeFiles/vespamalloc_mallocdst16.dir/mallocdst16.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
`
